### ISSUE TITLE
use classes

### ISSUE THREAD

**Issue by rimmesbe** [madtom85/prj-rev-bwfs-dasmoto#4]
This would be a good place to use a class. We want to keep our strong tags as close to default styling as we can incase we want to use them in other locations. Classes can also add some semantic value to the section being styled.
.price { color: blue; }
Strong tags default to bold as well.

https://github.com/madtom85/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/resources/css/styles.css#L17

**Comment by madtom85** [comment]
How do I make the class work only for the specified portion that should be blue?

**Comment by madtom85** [comment]
I guess I found the answer, I used a span tag with the class to change that.

**Comment by rimmesbe** [comment]
strong tags are just like span tags, only they default to bold font. Just give the strong tag the class.
